# $\S3$. Linear maps and matrices

**Author**: [Gilyoung Cheong](https://www.linkedin.com/in/gycheong/)

**References**
* ["Linear Algebra Done Wrong" by Sergei Treil](https://sites.google.com/a/brown.edu/sergei-treil-homepage/linear-algebra-done-wrong)

Let $V$ and $W$ be vector spaces over $\mathbb{F}$. A map $T : V \rightarrow W$ is said to be **linear** (or more precisely **$\mathbb{F}$-linear**) if

* $T(\boldsymbol{u} + \boldsymbol{v}) = T(\boldsymbol{u}) + T(\boldsymbol{v})$ for all $\boldsymbol{u}, \boldsymbol{v} \in V$ and
* $T(a \boldsymbol{v}) = a T(\boldsymbol{v})$ for all $\boldsymbol{v} \in V$ and $a \in \mathbb{F}$.

**Exercise.** Given $n \in \mathbb{Z}_{\geq 1}$, take
* $V = \mathbb{R}[t]_{\leq n}$ and
* $W = \mathbb{R}[t]_{\leq n-1}$.

Define $T : V \rightarrow W$ by $f(t) \mapsto f'(t)$, taking derivative. Show that $T$ is a linear map.

**Exercise**. Given an $m \times n$ matrix $X$ over $\mathbb{F}$, explain how $X$ can be thought as a linear map $X : \mathbb{F}^n \rightarrow \mathbb{F}^m$ by multiplication on the left.

**HW 1 Problem 2**. Given a real number $\theta \geq 0$. Write down a $2 \times 2$ matrix $X$ that defines a linear map $X : \mathbb{R}^2 \rightarrow \mathbb{R}^2$ that rotates any vector by $\theta$ (in radian).

**Exercise**. Given a linear map $T : \mathbb{F}^n \rightarrow \mathbb{F}^m$, show that the $m \times n$ matrix $X$ whose columns are given by $T(\boldsymbol{e}_1), \dots, T(\boldsymbol{e}_n)$ is equal to $T$ as a linear map from $\mathbb{F}^n$ to $\mathbb{F}^m$.

**Exercise**. Let $X$ be an $m \times n$ matrix with columns $\boldsymbol{x}_1, \dots, \boldsymbol{x}_n \in \mathbb{R}^m$. For any
$$\boldsymbol{v} = \begin{bmatrix}
v_1 \\
v_2 \\
\vdots \\
v_m
\end{bmatrix} \in \mathbb{R}^n,$$

show that

$$X \boldsymbol{v} = v_1\boldsymbol{x}_1 + \cdots + v_n\boldsymbol{x}_n.$$

**HW 1 Problem 3** Fix any $n \in \mathbb{Z}_{\geq 1}$ and let $X = (x_{ij})_{i,j=1}^{n}$ be any $n \times n$ matrix such that every entry is $0$ except the supdiagonal entries (i.e., the entries of the form $x_{i,i+1}$). Show that $X^n = 0$.

In [6]:
# This is not a proof, but an illustration

import numpy as np

X = np.matrix([[0, 2, 0, 0], 
     [0, 0, 3, 0],
     [0, 0, 0, 9],
     [0, 0, 0, 0]])

print(f"X = \n {X}")
print(f"X^2 = \n {X**2}")
print(f"X^3 = \n {X**3}")
print(f"X^4 = \n {X**4}")

X = 
 [[0 2 0 0]
 [0 0 3 0]
 [0 0 0 9]
 [0 0 0 0]]
X^2 = 
 [[ 0  0  6  0]
 [ 0  0  0 27]
 [ 0  0  0  0]
 [ 0  0  0  0]]
X^3 = 
 [[ 0  0  0 54]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]
X^4 = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
